---

apiVersion: v1
kind: Secret
metadata:
  name: supabase-secrets
  namespace: supabase
type: Opaque
stringData:
  postgres-db: postgres
  postgres-user: postgres
  postgres-password: postgres

  pgadmin-email: admin@local.dev
  pgadmin-password: admin

  jwt-secret: super-secret-jwt-token-with-at-least-32-chars
