apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: registry-ns
  name: registry-data-storage-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
