apiVersion: v1
kind: Secret
metadata:
  namespace: listmonk-ns
  name: listmonk-secrets
type: Opaque
stringData:
  postgres-user: listmonk
  postgres-password: listmonk
  postgres-db: listmonk
  config.toml: |
    [app]
    address = "0.0.0.0:9000"

    # Database.
    [db]
    host = "listmonk-db-service"
    port = 5432
    user = "listmonk"
    password = "listmonk"
    database = "listmonk"
    ssl_mode = "disable"
    max_open = 25
    max_idle = 25
    max_lifetime = "300s"
