apiVersion: v1
kind: Service
metadata:
  namespace: bitbucket-ns
  name: bitbucket-service
spec:
  selector:
    app: bitbucket
  ports:
  - name: bbport
    protocol: TCP
    port: 7990
    targetPort: 7990
  - name: bbport2
    protocol: TCP
    port: 7999
    targetPort: 7999
