apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: bitbucket-ns
  name: bitbucket-storage-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

      
