apiVersion: v1
kind: Service
metadata:
  namespace: apprise-ns
  name: apprise-service
spec:
  selector:
    app: apprise
  ports:
  - name: apprise-port
    protocol: TCP
    port: 8000
    targetPort: 8000
