apiVersion: v1
kind: Service
metadata:
  namespace: automq-ns
spec:
  selector:
    app: automq
  ports:
  - name: automq-port
    protocol: TCP
    port: 9092
    targetPort: 9092
  - name: automq-mgmt-port
    protocol: TCP
    port: 8080
    targetPort: 8080
