apiVersion: v1
kind: Secret
metadata:
  namespace: postiz-ns
  name: postiz-secrets
type: Opaque
stringData:
  postgres-user: postiz-user
  postgres-password: postiz-password
  postgres-db: postiz-db-local
  database-url: postgresql://postiz-user:postiz-password@postiz-db-service:5432/postiz-db-local
  jwt-secret: change-me-to-a-random-string-per-install
  openai-api-key: ""
  x-api-key: ""
  x-api-secret: ""
  linkedin-client-secret: ""
  reddit-client-secret: ""
  github-client-secret: ""
  beehive-api-key: ""
  threads-app-secret: ""
  facebook-app-secret: ""
  youtube-client-secret: ""
  tiktok-client-secret: ""
  pinterest-client-secret: ""
  dribbble-client-secret: ""
  discord-client-secret: ""
  discord-bot-token-id: ""
  slack-secret: ""
  slack-signing-secret: ""
  mastodon-client-secret: ""
  stripe-secret-key: ""
  stripe-signing-key: ""
  stripe-signing-key-connect: ""
---
apiVersion: v1
kind: Secret
metadata:
  namespace: postiz-ns
  name: postiz-temporal-secrets
type: Opaque
stringData:
  postgres-user: temporal
  postgres-password: temporal
