apiVersion: v1
kind: Service
metadata:
  namespace: n8n-ns
  name: n8n-service
spec:
  type: ClusterIP
  selector:
    app: n8n-deployment
  ports:
  - name: http
    protocol: TCP
    port: 5678
    targetPort: 5678
