apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: filebrowser-ns
  name: filebrowser-data-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: filebrowser-ns
  name: filebrowser-database-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
