apiVersion: v1
kind: Service
metadata:
  namespace: documentdb-ns
  name: documentdb-service
spec:
  selector:
    app: documentdb
  ports:
  - name: http
    protocol: TCP
    port: 10260
    targetPort: 10260
