apiVersion: v1
kind: Secret
metadata:
  namespace: portabase-ns
  name: portabase-secrets
type: Opaque
stringData:
  postgres-user: devuser
  postgres-password: changeme
  postgres-db: devdb
  database-url: postgresql://devuser:changeme@portabase-db-service:5432/devdb?schema=public
  project-secret: ""
  smtp-password: ""
  auth-oidc-secret: ""
  auth-social-secret: ""
