apiVersion: v1
kind: ConfigMap
metadata:
  namespace: authentik-ns
  name: authentik-config
data:
  AUTHENTIK_REDIS__HOST: authentik-redis-service
  AUTHENTIK_POSTGRESQL__HOST: authentik-db-service
  AUTHENTIK_BOOTSTRAP_USERNAME: akadmin
  AUTHENTIK_BOOTSTRAP_EMAIL: admin@example.com
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: authentik-ns
  name: authentik-db-config
data:
  POSTGRES_USER: authentik
  POSTGRES_DB: authentik
