apiVersion: v1
kind: Secret
metadata:
  namespace: authentik-ns
  name: authentik-secrets
type: Opaque
stringData:
  postgres-user: authentik
  postgres-password: authentik
  postgres-db: authentik
  secret-key: please_change_this_to_a_long_random_string
  bootstrap-password: ChangeMe123!
