apiVersion: v1
kind: ConfigMap
metadata:
  namespace: splunk-ns
  name: splunk-config
data:
  SPLUNK_START_ARGS: "--accept-license"
  SPLUNK_GENERAL_TERMS: "--accept-sgt-current-at-splunk-com"
  SPLNK_PASSWORD: "YourStrongPassword123!"
