apiVersion: v1
kind: Secret
metadata:
  namespace: bugzilla-ns
  name: bugzilla-secrets
type: Opaque
stringData:
  db-password: bugzilla
  mysql-root-password: rootpassword
  mysql-user: bugzilla
  mysql-password: bugzilla
  mysql-database: bugzilla
