apiVersion: v1
kind: Service
metadata:
  namespace: nessus-ns
  name: nessus-service
spec:
  selector:
    app: nessus
  ports:
  - name: nessus-port
    protocol: TCP
    port: 8834
    targetPort: 8834
