apiVersion: batch/v1
kind: Job
metadata:
  namespace: affine-ns
  name: affine-migration
spec:
  template:
    metadata:
      labels:
        app: affine-migration
    spec:
      restartPolicy: OnFailure
      containers:
      - name: migration
        image: ghcr.io/toeverything/affine:stable
        command:
        - sh
        - -c
        - node ./scripts/self-host-predeploy.js
        env:
        - name: REDIS_SERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: affine-config
              key: REDIS_SERVER_HOST
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: affine-secrets
              key: database-url
        volumeMounts:
        - name: affine-storage
          mountPath: /root/.affine/storage
        - name: affine-config
          mountPath: /root/.affine/config
      volumes:
      - name: affine-storage
        persistentVolumeClaim:
          claimName: affine-storage-claim
      - name: affine-config
        persistentVolumeClaim:
          claimName: affine-config-storage-claim
