apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: elasticsearch-ns
  name: elasticsearch-data-storage-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
