apiVersion: v1
kind: Service
metadata:
  namespace: couchdb-ns
  name: couchdb-service
spec:
  selector:
    app: couchdb
  ports:
  - name: couchdb-port
    protocol: TCP
    port: 5984
    targetPort: 5984
