apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: httpd-pvc
  namespace: k8s-collections
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath
