apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: fluent-bit-ns
  name: fluent-bit-conf-storage-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: fluent-bit-ns
  name: fluent-bit-parser-conf-storage-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: fluent-bit-ns
  name: fluent-bit-logs-storage-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
