apiVersion: v1
kind: Secret
metadata:
  namespace: mattermost-ns
  name: mattermost-secrets
type: Opaque
stringData:
  postgres-user: mattermost
  postgres-password: changeme
  postgres-db: mattermost
  datasource: postgres://mattermost:changeme@mattermost-db-service:5432/mattermost?sslmode=disable
