apiVersion: v1
kind: Secret
metadata:
  namespace: atlassian-jira-ns
  name: jira-secrets
type: Opaque
stringData:
  postgres-user: admin
  postgres-password: Password@123
  postgres-db: jiradb
  jdbc-user: admin
  jdbc-password: Password@123
