apiVersion: v1
kind: Secret
metadata:
  namespace: affine-ns
  name: affine-secrets
type: Opaque
stringData:
  postgres-user: affine
  postgres-password: affine
  postgres-db: affine
  database-url: postgresql://affine:affine@affine-db-service:5432/affine
