apiVersion: v1
kind: ConfigMap
metadata:
  namespace: activepieces-ns
  name: activepieces-config
data:
  AP_REDIS_HOST: activepieces-redis-service
  AP_REDIS_PORT: "6379"
  AP_DATABASE_TYPE: postgres
  AP_POSTGRES_HOST: activepieces-db-service
  AP_POSTGRES_PORT: "5432"
  AP_FRONTEND_URL: http://localhost:8080
  AP_TELEMETRY_ENABLED: "false"
  AP_SYNC_PIECES_ON_STARTUP: "false"
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: activepieces-ns
  name: activepieces-db-config
data:
  POSTGRES_USER: activepieces
  POSTGRES_DB: activepieces
