apiVersion: v1
kind: Secret
metadata:
  namespace: activepieces-ns
  name: activepieces-secrets
type: Opaque
stringData:
  postgres-user: activepieces
  postgres-password: activepieces
  postgres-db: activepieces
  encryption-key: 703ee45e7a485db357aa8517a2793ddf
  jwt-secret: supersecretjwtkey
