name: Validate Kubernetes Manifests

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Validate Kubernetes manifests
      shell: bash
      run: |
        set -e

        find . -mindepth 1 -maxdepth 1 -type d \
          ! -name ".github" \
          -print0 |
        while IFS= read -r -d '' dir; do
          if find "$dir" -type f \( -name "*.yaml" -o -name "*.yml" \) -print -quit | grep -q .; then
            echo "Validating: $dir"
            kubectl apply --dry-run=client \
            --validate=false \
            -R -f "$dir"
          fi
        done
